fname = input("Enter First Name:")
lname = input("Enter Last Name:")
city = input("Enter City:")
state = input("Enter State:")
country = input("Enter Country:")

print("****Biodata****")
print("First Name:",fname)
print("Last Name:",lname)
print("City:",city)
print("State:",state)
print("Country:",country)
